### ISSUE TITLE
rxjs__WEBPACK_IMPORTED_MODULE_4__.Observable.throw is not a function

### ISSUE THREAD

**Issue by oggers** [plone/plone.restapi-angular#92]
Hi,

when the login fails I get the error:
`rxjs__WEBPACK_IMPORTED_MODULE_4__.Observable.throw is not a function`

To fix it I put
`import 'rxjs/add/observable/throw';`
in services/authentication.service.ts

**Comment by ebrehault** [comment]
It looks like you are not using the proper version of Angular and/or RxJS. It works with Angular 7.2.0.

Note: plone.restapi-angular is kind of deprecated now, in favor of Grange (https://github.com/guillotinaweb/grange) which is meant to work with a Guillotina backend but which is compliant with Plone RESTAPI

**Comment by oggers** [comment]
I was using angular 8, and it seems that plone.restapi-angular isn't compatible with it.

As suggested by ebrehault I have tested Grange and it seems to resolve the issues I had. So I have changed to Grange.
